type StockData = {
  id: number;
  name: string;
  symbol: string;
  last: string;
  open: string;
  high: string;
  low: string;
  chg: string;
  chgper: string;
  vol: string;
  time: string;
};
export const data: StockData[] = [
  {
    id: 1,
    name: 'Tesla',
    symbol: 'TLS',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '+6%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 2,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '+6%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 3,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '+6%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 4,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '-3%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 5,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '-6%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 6,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '+6%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 7,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '-6%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 8,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '-6%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 9,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '+6%',
    vol: '2M',
    time: '09/09',
  },
  {
    id: 10,
    name: 'Apple',
    symbol: 'AAPL',
    last: '234',
    open: '240',
    high: '260',
    low: '180',
    chg: '6',
    chgper: '-6%',
    vol: '2M',
    time: '09/09',
  },
];
